### ISSUE TITLE
TutorialBars.png

### ISSUE THREAD

**Issue by Snakiestgoose** [FoolsLynx/TutorialMod#1]
Hi, I am currently going through your great tutorial and have been using some of the assets provided in this repo for following along. I'm in the WORLD GENERATION AND LOCALISATION tutorial right now and noticed the TutorialBars.png file wasn't updated to have the rare bar in placeStyle 1.

**Comment by FoolsLynx** [comment]
Thank you for noticing this. Sorry for the late notice. I will update this right now. Surprised I never updated that in the first place.
